from __future__ import annotations

import json
import os
import re
import tempfile
import threading
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping


# ============================================================
# PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]
CONTEXT_DIR = PROJECT_ROOT / "backend" / "context"
DATA_DIR = PROJECT_ROOT / "backend" / "data"

IDENTITY_FILE = CONTEXT_DIR / "Identity.md"
SOUL_FILE = CONTEXT_DIR / "Soul.md"
USER_FILE = CONTEXT_DIR / "User.md"

AUDIT_FILE = DATA_DIR / "context_changes.jsonl"


# ============================================================
# LIMITS
# ============================================================

MAX_CHANGES = 8

MAX_KEY_LENGTH = 160
MAX_VALUE_LENGTH = 2000
MAX_REASON_LENGTH = 1000
MAX_SECTION_LENGTH = 160

MAX_FILE_SIZE = 100_000

ALLOWED_TARGETS = {
    "user": USER_FILE,
    "soul": SOUL_FILE,
    "identity": IDENTITY_FILE,
}

ALLOWED_OPERATIONS = {
    "upsert",
    "remove",
}


# ============================================================
# SAFETY
# ============================================================

# These categories should never be silently persisted from an
# ordinary conversational statement.
#
# Explicit user requests can still be handled, but the updater
# remains conservative.
SENSITIVE_KEY_PATTERNS = (
    r"\bpassword\b",
    r"\bpasscode\b",
    r"\bsecret\b",
    r"\bapi[_ -]?key\b",
    r"\btoken\b",
    r"\bprivate[_ -]?key\b",
    r"\bcredit[_ -]?card\b",
    r"\bbank[_ -]?account\b",
    r"\bmedical\b",
    r"\bhealth\b",
    r"\bdiagnos",
    r"\bmedication\b",
    r"\bpolitical\b",
    r"\breligion\b",
    r"\bsexual\b",
    r"\bsexuality\b",
    r"\bethnicity\b",
    r"\brace\b",
    r"\bcriminal\b",
    r"\bexact[_ -]?address\b",
)

_SENSITIVE_KEY_RE = re.compile(
    "|".join(SENSITIVE_KEY_PATTERNS),
    re.IGNORECASE,
)


# ============================================================
# LOCK
# ============================================================

_CONTEXT_LOCK = threading.RLock()


# ============================================================
# DATA CLASSES
# ============================================================

@dataclass(slots=True)
class ContextChange:
    """
    One requested modification to a context file.
    """

    operation: str
    key: str

    new_value: str = ""
    old_value: str | None = None

    section: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "operation": self.operation,
            "key": self.key,
            "new_value": self.new_value,
            "old_value": self.old_value,
            "section": self.section,
        }

    @classmethod
    def from_mapping(
        cls,
        value: Mapping[str, Any],
    ) -> "ContextChange":
        return cls(
            operation=str(value.get("operation", "")).strip().lower(),
            key=str(value.get("key", "")).strip(),
            new_value=str(value.get("new_value", "") or ""),
            old_value=(
                None
                if value.get("old_value") is None
                else str(value.get("old_value"))
            ),
            section=str(value.get("section", "") or "").strip(),
        )


@dataclass(slots=True)
class ContextUpdate:
    """
    Structured proposal generated by the semantic persistence gate.
    """

    update: bool = False

    target: str = ""

    explicit: bool = False

    reason: str = ""

    changes: list[ContextChange] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "update": self.update,
            "target": self.target,
            "explicit": self.explicit,
            "reason": self.reason,
            "changes": [
                change.to_dict()
                for change in self.changes
            ],
        }

    @classmethod
    def from_mapping(
        cls,
        value: Mapping[str, Any] | None,
    ) -> "ContextUpdate":
        if not isinstance(value, Mapping):
            return cls()

        raw_changes = value.get("changes", [])

        if not isinstance(raw_changes, list):
            raw_changes = []

        changes: list[ContextChange] = []

        for raw_change in raw_changes:
            if not isinstance(raw_change, Mapping):
                continue

            try:
                changes.append(
                    ContextChange.from_mapping(raw_change)
                )
            except Exception:
                continue

        return cls(
            update=bool(value.get("update", False)),
            target=str(value.get("target", "") or "")
            .strip()
            .lower(),
            explicit=bool(value.get("explicit", False)),
            reason=str(value.get("reason", "") or ""),
            changes=changes,
        )


@dataclass(slots=True)
class ContextUpdateResult:
    """
    Result returned after attempting to apply a context update.
    """

    success: bool

    target: str = ""

    applied_count: int = 0

    rejected_count: int = 0

    message: str = ""

    applied_changes: list[dict[str, Any]] = field(
        default_factory=list
    )

    rejected_changes: list[dict[str, Any]] = field(
        default_factory=list
    )

    def to_dict(self) -> dict[str, Any]:
        return {
            "success": self.success,
            "target": self.target,
            "applied_count": self.applied_count,
            "rejected_count": self.rejected_count,
            "message": self.message,
            "applied_changes": self.applied_changes,
            "rejected_changes": self.rejected_changes,
        }


# ============================================================
# CONTEXT MANAGER
# ============================================================

class ContextUpdateManager:
    """
    Safe writer for ZOE's persistent Markdown context.

    Responsibilities
    ----------------
    - Read current Identity/Soul/User context.
    - Validate semantic update proposals.
    - Apply only structured modifications.
    - Prevent arbitrary filesystem writes.
    - Prevent ambiguous replacements.
    - Verify expected old values.
    - Atomically replace files.
    - Write an audit record for successful changes.

    The LLM NEVER receives direct filesystem write access.
    """

    def __init__(
        self,
        *,
        identity_file: Path = IDENTITY_FILE,
        soul_file: Path = SOUL_FILE,
        user_file: Path = USER_FILE,
        audit_file: Path = AUDIT_FILE,
    ) -> None:
        self.identity_file = Path(identity_file)
        self.soul_file = Path(soul_file)
        self.user_file = Path(user_file)
        self.audit_file = Path(audit_file)

        self._targets: dict[str, Path] = {
            "identity": self.identity_file,
            "soul": self.soul_file,
            "user": self.user_file,
        }

        self._ensure_directories()

    # ========================================================
    # PUBLIC API
    # ========================================================

    def snapshot(
        self,
        *,
        max_chars: int = 5000,
    ) -> dict[str, str]:
        """
        Return the current persistent context.

        This is intended for the semantic update gate.
        """

        result: dict[str, str] = {}

        with _CONTEXT_LOCK:
            for target, path in self._targets.items():
                result[target] = self._read_file(
                    path,
                    max_chars=max_chars,
                )

        return result

    def read_target(
        self,
        target: str,
    ) -> str:
        """
        Read one context file.
        """

        normalized_target = self._normalize_target(target)

        path = self._targets[normalized_target]

        with _CONTEXT_LOCK:
            return self._read_file(
                path,
                max_chars=None,
            )

    def apply(
        self,
        update: ContextUpdate,
    ) -> ContextUpdateResult:
        """
        Validate and apply a structured update.

        This method is intentionally fail-closed.
        """

        with _CONTEXT_LOCK:
            validation_error = self._validate_update(update)

            if validation_error:
                return ContextUpdateResult(
                    success=False,
                    target=update.target,
                    rejected_count=len(update.changes),
                    message=validation_error,
                )

            target = self._normalize_target(
                update.target
            )

            path = self._targets[target]

            if not path.exists():
                return ContextUpdateResult(
                    success=False,
                    target=target,
                    rejected_count=len(update.changes),
                    message=f"Context file does not exist: {path}",
                )

            try:
                original_text = self._read_file(
                    path,
                    max_chars=None,
                )
            except Exception as exc:
                return ContextUpdateResult(
                    success=False,
                    target=target,
                    rejected_count=len(update.changes),
                    message=f"Failed to read context file: {exc}",
                )

            current_text = original_text

            applied: list[dict[str, Any]] = []
            rejected: list[dict[str, Any]] = []

            for change in update.changes:
                try:
                    current_text, result = self._apply_change(
                        current_text,
                        change,
                        target=target,
                        explicit=update.explicit,
                    )

                    if result["applied"]:
                        applied.append(result)
                    else:
                        rejected.append(result)

                except Exception as exc:
                    rejected.append(
                        {
                            "applied": False,
                            "operation": change.operation,
                            "key": change.key,
                            "message": str(exc),
                        }
                    )

            # Nothing changed.
            if current_text == original_text:
                return ContextUpdateResult(
                    success=(
                        len(applied) > 0
                        and len(rejected) == 0
                    ),
                    target=target,
                    applied_count=len(applied),
                    rejected_count=len(rejected),
                    message=(
                        "No file changes were necessary."
                        if not applied
                        else "Changes were already reflected in the file."
                    ),
                    applied_changes=applied,
                    rejected_changes=rejected,
                )

            # Fail closed if ANY requested change was rejected.
            #
            # This prevents a partially applied multi-change proposal
            # from silently producing an inconsistent profile.
            if rejected:
                return ContextUpdateResult(
                    success=False,
                    target=target,
                    applied_count=0,
                    rejected_count=len(rejected),
                    message=(
                        "Update rejected because one or more "
                        "requested changes could not be validated."
                    ),
                    applied_changes=[],
                    rejected_changes=rejected,
                )

            try:
                self._atomic_write(
                    path,
                    current_text,
                )
            except Exception as exc:
                return ContextUpdateResult(
                    success=False,
                    target=target,
                    rejected_count=len(applied),
                    message=f"Failed to write context file: {exc}",
                    applied_changes=[],
                    rejected_changes=applied,
                )

            self._write_audit_record(
                target=target,
                path=path,
                update=update,
                changes=applied,
            )

            return ContextUpdateResult(
                success=True,
                target=target,
                applied_count=len(applied),
                rejected_count=0,
                message=(
                    f"Applied {len(applied)} change(s) "
                    f"to {path.name}."
                ),
                applied_changes=applied,
                rejected_changes=[],
            )

    # ========================================================
    # VALIDATION
    # ========================================================

    def _validate_update(
        self,
        update: ContextUpdate,
    ) -> str | None:
        if not isinstance(update, ContextUpdate):
            return "Invalid context update object."

        if not update.update:
            return "Update flag is false."

        target = self._normalize_target(update.target)

        if target not in ALLOWED_TARGETS:
            return f"Invalid context target: {target!r}"

        if not update.changes:
            return "Context update contains no changes."

        if len(update.changes) > MAX_CHANGES:
            return (
                f"Too many changes: {len(update.changes)}. "
                f"Maximum is {MAX_CHANGES}."
            )

        reason = update.reason.strip()

        if len(reason) > MAX_REASON_LENGTH:
            return "Update reason is too long."

        # Soul and Identity are never silently changed.
        if target in {"soul", "identity"}:
            if not update.explicit:
                return (
                    f"{target.title()}.md requires an explicit "
                    "permanent-change request."
                )

        for change in update.changes:
            error = self._validate_change(
                change,
                target=target,
                explicit=update.explicit,
            )

            if error:
                return error

        return None

    def _validate_change(
        self,
        change: ContextChange,
        *,
        target: str,
        explicit: bool,
    ) -> str | None:
        if not isinstance(change, ContextChange):
            return "Invalid context change."

        operation = change.operation.strip().lower()

        if operation not in ALLOWED_OPERATIONS:
            return (
                f"Unsupported operation: {operation!r}. "
                f"Allowed: {sorted(ALLOWED_OPERATIONS)}"
            )

        key = change.key.strip()

        if not key:
            return "Context change has an empty key."

        if len(key) > MAX_KEY_LENGTH:
            return f"Context key is too long: {key!r}"

        if "\n" in key or "\r" in key:
            return "Context key cannot contain newlines."

        section = change.section.strip()

        if len(section) > MAX_SECTION_LENGTH:
            return "Context section is too long."

        if "\n" in section or "\r" in section:
            return "Context section cannot contain newlines."

        new_value = change.new_value

        if "\n" in new_value or "\r" in new_value:
            return (
                f"Value for {key!r} must be a single-line value."
            )

        if len(new_value) > MAX_VALUE_LENGTH:
            return (
                f"Value for {key!r} is too long."
            )

        if change.old_value is not None:
            if "\n" in change.old_value or "\r" in change.old_value:
                return "Expected old value cannot contain newlines."

            if len(change.old_value) > MAX_VALUE_LENGTH:
                return "Expected old value is too long."

        # Never permit secrets to be persisted automatically.
        if _SENSITIVE_KEY_RE.search(key):
            if not explicit:
                return (
                    f"Sensitive context key {key!r} requires "
                    "an explicit user request."
                )

        # Removal never needs a new value.
        if operation == "remove":
            return None

        if not new_value.strip():
            return (
                f"New value for {key!r} cannot be empty."
            )

        return None

    # ========================================================
    # CHANGE APPLICATION
    # ========================================================

    def _apply_change(
        self,
        text: str,
        change: ContextChange,
        *,
        target: str,
        explicit: bool,
    ) -> tuple[str, dict[str, Any]]:
        operation = change.operation.strip().lower()

        lines = text.splitlines(
            keepends=True,
        )

        section_start, section_end = self._section_bounds(
            lines,
            change.section,
        )

        matches = self._find_key_matches(
            lines,
            change.key,
            start=section_start,
            end=section_end,
        )

        if len(matches) > 1:
            raise ValueError(
                f"Ambiguous key {change.key!r}: "
                f"{len(matches)} matching entries found."
            )

        if operation == "upsert":
            if len(matches) == 1:
                index, match = matches[0]

                current_value = match.group(2).strip()

                if change.old_value is None:
                    raise ValueError(
                        f"Refusing to overwrite {change.key!r} "
                        "without an expected old value."
                    )

                if not self._values_equal(
                    current_value,
                    change.old_value,
                ):
                    raise ValueError(
                        f"Old value mismatch for {change.key!r}. "
                        f"Expected {change.old_value!r}, "
                        f"found {current_value!r}."
                    )

                new_line = (
                    f"{match.group(1)}"
                    f"{change.new_value.strip()}"
                    f"{self._line_ending(lines[index])}"
                )

                lines[index] = new_line

                return (
                    "".join(lines),
                    {
                        "applied": True,
                        "operation": "replace",
                        "key": change.key,
                        "old_value": current_value,
                        "new_value": change.new_value.strip(),
                        "section": change.section,
                        "target": target,
                    },
                )

            # No existing entry -> add it.
            insert_at = self._insertion_index(
                lines,
                section_start=section_start,
                section_end=section_end,
                section=change.section,
            )

            new_line = (
                f"{change.key.strip()}: "
                f"{change.new_value.strip()}\n"
            )

            lines.insert(
                insert_at,
                new_line,
            )

            return (
                "".join(lines),
                {
                    "applied": True,
                    "operation": "add",
                    "key": change.key,
                    "old_value": None,
                    "new_value": change.new_value.strip(),
                    "section": change.section,
                    "target": target,
                },
            )

        if operation == "remove":
            if len(matches) != 1:
                raise ValueError(
                    f"Cannot remove {change.key!r}: "
                    "exactly one existing entry is required."
                )

            index, match = matches[0]

            current_value = match.group(2).strip()

            if change.old_value is not None:
                if not self._values_equal(
                    current_value,
                    change.old_value,
                ):
                    raise ValueError(
                        f"Old value mismatch for {change.key!r}. "
                        f"Expected {change.old_value!r}, "
                        f"found {current_value!r}."
                    )

            del lines[index]

            return (
                "".join(lines),
                {
                    "applied": True,
                    "operation": "remove",
                    "key": change.key,
                    "old_value": current_value,
                    "new_value": None,
                    "section": change.section,
                    "target": target,
                },
            )

        raise ValueError(
            f"Unsupported operation: {operation!r}"
        )

    # ========================================================
    # MARKDOWN PARSING
    # ========================================================

    def _find_key_matches(
        self,
        lines: list[str],
        key: str,
        *,
        start: int,
        end: int,
    ) -> list[tuple[int, re.Match[str]]]:
        escaped_key = re.escape(
            key.strip()
        )

        pattern = re.compile(
            rf"^"
            rf"(\s*"
            rf"(?:[-*]\s+)?"
            rf"(?:\*\*)?"
            rf"{escaped_key}"
            rf"(?:\*\*)?"
            rf"\s*:\s*)"
            rf"(.*?)"
            rf"\s*$",
            re.IGNORECASE,
        )

        matches: list[tuple[int, re.Match[str]]] = []

        for index in range(
            max(0, start),
            min(len(lines), end),
        ):
            match = pattern.match(
                lines[index].rstrip("\r\n")
            )

            if match:
                matches.append(
                    (index, match)
                )

        return matches

    def _section_bounds(
        self,
        lines: list[str],
        section: str,
    ) -> tuple[int, int]:
        """
        Return [start, end) for a Markdown section.

        If no section is supplied, the entire document is searched.
        """

        if not section:
            return 0, len(lines)

        wanted = self._normalize_heading(
            section
        )

        heading_pattern = re.compile(
            r"^\s*#{1,6}\s+(.+?)\s*$"
        )

        section_start: int | None = None
        section_level = 0

        for index, raw_line in enumerate(lines):
            line = raw_line.rstrip("\r\n")

            match = heading_pattern.match(line)

            if not match:
                continue

            heading_text = self._normalize_heading(
                match.group(1)
            )

            if section_start is None:
                if heading_text == wanted:
                    section_start = index + 1
                    section_level = (
                        len(
                            line
                        )
                        - len(
                            line.lstrip("#")
                        )
                    )

                    # The expression above can be distorted by
                    # whitespace. Recompute from the actual heading.
                    section_level = len(
                        line
                    ) - len(
                        line.lstrip()
                    )

                    hash_match = re.match(
                        r"^\s*(#{1,6})\s+",
                        line,
                    )

                    if hash_match:
                        section_level = len(
                            hash_match.group(1)
                        )

                    continue

            else:
                hash_match = re.match(
                    r"^\s*(#{1,6})\s+",
                    line,
                )

                if not hash_match:
                    continue

                level = len(
                    hash_match.group(1)
                )

                if level <= section_level:
                    return (
                        section_start,
                        index,
                    )

        if section_start is None:
            raise ValueError(
                f"Markdown section {section!r} was not found."
            )

        return section_start, len(lines)

    def _insertion_index(
        self,
        lines: list[str],
        *,
        section_start: int,
        section_end: int,
        section: str,
    ) -> int:
        if not section:
            # Keep the file readable.
            if lines and lines[-1].strip():
                return len(lines)

            return len(lines)

        # Insert immediately before the next section heading.
        index = section_end

        while (
            index > section_start
            and index - 1 < len(lines)
            and not lines[index - 1].strip()
        ):
            index -= 1

        return index

    @staticmethod
    def _normalize_heading(
        value: str,
    ) -> str:
        value = value.strip()

        value = re.sub(
            r"^#{1,6}\s*",
            "",
            value,
        )

        value = value.strip(
            "*_` "
        )

        return re.sub(
            r"\s+",
            " ",
            value,
        ).casefold()

    @staticmethod
    def _values_equal(
        left: str,
        right: str,
    ) -> bool:
        def normalize(value: str) -> str:
            return re.sub(
                r"\s+",
                " ",
                value.strip(),
            ).casefold()

        return normalize(left) == normalize(right)

    @staticmethod
    def _line_ending(
        lines: list[str],
    ) -> str:
        for line in lines:
            if line.endswith("\r\n"):
                return "\r\n"

        return "\n"

    # ========================================================
    # FILE IO
    # ========================================================

    @staticmethod
    def _read_file(
        path: Path,
        *,
        max_chars: int | None,
    ) -> str:
        if not path.exists():
            return ""

        if not path.is_file():
            raise RuntimeError(
                f"Context path is not a file: {path}"
            )

        if path.stat().st_size > MAX_FILE_SIZE:
            raise RuntimeError(
                f"Context file is unexpectedly large: {path}"
            )

        text = path.read_text(
            encoding="utf-8",
        )

        if max_chars is not None:
            return text[:max_chars]

        return text

    @staticmethod
    def _atomic_write(
        path: Path,
        content: str,
    ) -> None:
        path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        original_mode: int | None = None

        if path.exists():
            try:
                original_mode = (
                    path.stat().st_mode
                    & 0o777
                )
            except OSError:
                original_mode = None

        fd, temporary_name = tempfile.mkstemp(
            prefix=f".{path.name}.",
            suffix=".tmp",
            dir=str(path.parent),
            text=True,
        )

        temporary_path = Path(
            temporary_name
        )

        try:
            with os.fdopen(
                fd,
                "w",
                encoding="utf-8",
                newline="",
            ) as handle:
                handle.write(content)
                handle.flush()
                os.fsync(handle.fileno())

            if original_mode is not None:
                try:
                    temporary_path.chmod(
                        original_mode
                    )
                except OSError:
                    pass

            os.replace(
                temporary_path,
                path,
            )

        except Exception:
            try:
                temporary_path.unlink(
                    missing_ok=True
                )
            except Exception:
                pass

            raise

    def _ensure_directories(
        self,
    ) -> None:
        CONTEXT_DIR.mkdir(
            parents=True,
            exist_ok=True,
        )

        DATA_DIR.mkdir(
            parents=True,
            exist_ok=True,
        )

    # ========================================================
    # AUDIT
    # ========================================================

    def _write_audit_record(
        self,
        *,
        target: str,
        path: Path,
        update: ContextUpdate,
        changes: list[dict[str, Any]],
    ) -> None:
        record = {
            "timestamp": datetime.now(
                timezone.utc
            ).isoformat(),
            "target": target,
            "file": str(path),
            "reason": update.reason[:MAX_REASON_LENGTH],
            "explicit": update.explicit,
            "changes": changes,
        }

        try:
            self.audit_file.parent.mkdir(
                parents=True,
                exist_ok=True,
            )

            with self.audit_file.open(
                "a",
                encoding="utf-8",
            ) as handle:
                handle.write(
                    json.dumps(
                        record,
                        ensure_ascii=False,
                        separators=(",", ":"),
                    )
                    + "\n"
                )

        except Exception as exc:
            # Audit failure must never roll back an already successful
            # context update.
            print(
                f"[CONTEXT] Audit write failed: {exc}"
            )

    # ========================================================
    # HELPERS
    # ========================================================

    @staticmethod
    def _normalize_target(
        target: str,
    ) -> str:
        normalized = str(
            target or ""
        ).strip().lower()

        aliases = {
            "user.md": "user",
            "user": "user",
            "soul.md": "soul",
            "soul": "soul",
            "identity.md": "identity",
            "identity": "identity",
        }

        return aliases.get(
            normalized,
            normalized,
        )


# ============================================================
# SINGLETON
# ============================================================

_default_manager: ContextUpdateManager | None = None
_default_manager_lock = threading.Lock()


def get_context_update_manager() -> ContextUpdateManager:
    global _default_manager

    if _default_manager is None:
        with _default_manager_lock:
            if _default_manager is None:
                _default_manager = (
                    ContextUpdateManager()
                )

    return _default_manager


# ============================================================
# CONVENIENCE API
# ============================================================

def apply_context_update(
    update: ContextUpdate,
) -> ContextUpdateResult:
    return get_context_update_manager().apply(
        update
    )


def get_context_snapshot(
    *,
    max_chars: int = 5000,
) -> dict[str, str]:
    return get_context_update_manager().snapshot(
        max_chars=max_chars
    )